# Generated by Django 5.2.16 on 2026-07-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_parameter',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
