# Generated by Django 5.2.16 on 2026-07-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_sitesettings_site_parameter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='email_notifications_enabled',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='disabled_channels',
            field=models.JSONField(default=list),
        ),
    ]
