# Generated by Django 5.2.16 on 2026-07-23 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_sitesettings_email_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='disabled_channels',
            new_name='notifications_disabled_channels',
        ),
    ]
