# Generated by Django 5.2.16 on 2026-07-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_disabled_channels_sitesettings_notifications_disabled_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tasks_notification_due_reminders_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
