# Generated by Django 5.2.16 on 2026-07-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_sitesettings_tasks_notification_due_reminders_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='notifications_disabled_channels',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notification_channels_email_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
