# Generated by Django 5.2.16 on 2026-07-29 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_sitesettings_notifications_disabled_channels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='notification_channels_email_enabled',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='tasks_notification_due_reminders_enabled',
        ),
    ]
