"""
Django settings for wupnext project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import sys
import warnings
from pathlib import Path
from shutil import which

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

SECRET_KEY = os.getenv('SECRET_KEY')

DEBUG = os.getenv('DEBUG') == 'True'

ALLOWED_HOSTS = [h for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()]

CSRF_TRUSTED_ORIGINS = [
    o for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]

# Required for OAuth as the proxy ends HTTPS connection
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

TESTING = 'test' in sys.argv


# Application definition

INSTALLED_APPS = [
    # JET admin
    'jet.dashboard',
    'jet',
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # MCP Server
    'mcp_server',
    # Tailwind
    'tailwind',
    'theme',
    'django_browser_reload',
    # Task queue / scheduler
    'django_q',
    # Project apps
    'common',
    'accounts',
    'tasks',
    'pomodoro',
    'notifications',
    # Django OAuth Toolkit. Listed last to allow template overriding
    'oauth2_provider',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',
]

ROOT_URLCONF = 'wupnext.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'common.context_processors.settings',
                'pomodoro.context_processors.pomodoro',
                'tasks.context_processors.sidebar',
            ],
        },
    },
]

WSGI_APPLICATION = 'wupnext.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db' / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation'
        '.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'accounts.CustomUser'

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# URL to use when referring to static files in templates
STATIC_URL = '/static/'

# Absolute path where collectstatic will gather all static files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'  # This directory will be created by Django

# Additional directories for Django to search for static files
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Global static folder in the project root
]

STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Tailwind
TAILWIND_APP_NAME = 'theme'

NPM_BIN_PATH = which('npm')

# Jet
X_FRAME_OPTIONS = 'SAMEORIGIN'

JET_THEMES = [
    {'theme': 'default', 'color': '#47bac1', 'title': 'Default'},
    {'theme': 'green', 'color': '#44b78b', 'title': 'Green'},
    {'theme': 'light-green', 'color': '#2faa60', 'title': 'Light Green'},
    {'theme': 'light-violet', 'color': '#a464c4', 'title': 'Light Violet'},
    {'theme': 'light-blue', 'color': '#5EADDE', 'title': 'Light Blue'},
    {'theme': 'light-gray', 'color': '#222', 'title': 'Light Gray'},
]

# Email
LIVE_EMAIL_BACKEND = 'anymail.backends.resend.EmailBackend'

EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG else LIVE_EMAIL_BACKEND,
)

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'WupNext <onboarding@resend.dev>')

ANYMAIL = {
    'RESEND_API_KEY': os.getenv('RESEND_API_KEY', ''),
}

SITE_URL = os.getenv('SITE_URL', '').rstrip('/')


# Django Q2 (ORM broker — no Redis/Celery)
Q_CLUSTER = {
    'name': 'wupnext',
    'workers': int(os.getenv('Q_WORKERS', '2')),
    'timeout': int(os.getenv('Q_TIMEOUT', '60')),
    'retry': int(os.getenv('Q_RETRY', '120')),
    'catch_up': False,
    'orm': 'default',
    # django-q logs its cluster and worker startup at INFO on its own handler.
    'log_level': 'WARNING',
}


# Logging

# The MCP SDK declares a pydantic-settings field with an unresolved forward
# reference. There is nothing to fix on our side, and it prints on every start.
warnings.filterwarnings(
    'ignore', message=r"Field 'lifespan' has an incomplete definition"
)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'loggers': {
        'notifications': {
            'handlers': ['console'],
            'level': 'WARNING' if TESTING else 'INFO',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console'],
            'level': 'WARNING' if TESTING else 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}


# Accounts redirect urls
LOGIN_REDIRECT_URL = 'tasks:board'
LOGIN_URL = 'accounts:login'
LOGOUT_REDIRECT_URL = 'accounts:login'
LOGOUT_URL = 'accounts:logout'


# MCP Server
MCP_BASE_URL = os.getenv('MCP_BASE_URL', 'http://localhost:8000')

DJANGO_MCP_AUTHENTICATION_CLASSES = [
    'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
]

OAUTH2_PROVIDER = {
    'DCR_ENABLED': True,  # default False
    'DCR_REGISTRATION_PERMISSION_CLASSES': (
        'oauth2_provider.dcr.AllowAllDCRPermission',
    ),
    'OAUTH2_PROTECTED_RESOURCE_IDENTIFIER': f'{MCP_BASE_URL}/mcp',
    'OAUTH2_PROTECTED_RESOURCE_AUTHORIZATION_SERVERS': [MCP_BASE_URL],
}
