# Generated by Django 5.2.16 on 2026-07-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='disabled_channels',
            field=models.JSONField(default=list),
        ),
    ]
