# Generated by Django 5.2.16 on 2026-07-23 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userpreferences_disabled_channels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferences',
            old_name='disabled_channels',
            new_name='notifications_disabled_channels',
        ),
    ]
