# Generated by Django 5.2.16 on 2026-07-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_disabled_channels_userpreferences_notifications_disabled_channels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='notifications_disabled_channels',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notification_channels_email_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
