# Generated by Django 5.2.16 on 2026-07-29 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='notification_channels_email_enabled',
        ),
    ]
