# Generated by Django 5.2.16 on 2026-07-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userpreferences_notification_channels_email_enabled'),
        ('pomodoro', '0003_copy_user_preferences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreferences',
        ),
    ]
