# Generated by Django 5.2.16 on 2026-07-21 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('focus', 'Focus'), ('short', 'Short break'), ('long', 'Long break')], default='focus', max_length=5)),
                ('running', models.BooleanField(default=False)),
                ('ends_at_ms', models.BigIntegerField(blank=True, default=None, null=True)),
                ('remaining', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('completed', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
