# Generated by Django 5.0.6 on 2026-03-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
