# Generated by Django 5.0.6 on 2026-07-15 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_daily_scoping_and_chrono_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
