# Generated by Django 5.2.16 on 2026-07-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_options_task_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='group_position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
