# Generated by Django 5.2.16 on 2026-08-20 09:19

from django.db import migrations


def update_archive_tasks_from_parent(apps, schema_editor):
    Tasks = apps.get_model('tasks', 'Task')

    for task in Tasks.objects.filter(parent=None):
        if task.archived_at is None:
            task.subtasks.update(archived_at=None)
        else:
            task.subtasks.update(archived_at=task.archived_at)
    

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_backfill_task_positions'),
    ]

    operations = [
        migrations.RunPython(update_archive_tasks_from_parent)
    ]
