# Generated by Django 5.2.16 on 2026-07-29 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationlog_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannelSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email')], max_length=32, unique=True)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['channel'],
            },
        ),
        migrations.CreateModel(
            name='NotificationEventSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=64)),
                ('channel', models.CharField(choices=[('email', 'Email')], max_length=32)),
                ('enabled', models.BooleanField(default=False)),
                ('on_by_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['event', 'channel'],
                'constraints': [models.UniqueConstraint(fields=('event', 'channel'), name='unique_notification_event_switch')],
            },
        ),
        migrations.CreateModel(
            name='NotificationUserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=64)),
                ('channel', models.CharField(choices=[('email', 'Email')], max_length=32)),
                ('enabled', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event', 'channel'],
                'constraints': [models.UniqueConstraint(fields=('user', 'event', 'channel'), name='unique_notification_user_preference')],
            },
        ),
    ]
