# Generated by Django 5.2.16 on 2026-07-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_switches'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationchannelswitch',
            options={'ordering': ['channel'], 'verbose_name': 'channel switch', 'verbose_name_plural': 'channel switches'},
        ),
        migrations.AlterModelOptions(
            name='notificationeventswitch',
            options={'ordering': ['event', 'channel'], 'verbose_name': 'event switch', 'verbose_name_plural': 'event switches'},
        ),
    ]
