# Generated by Django 5.2.16 on 2026-08-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notificationchannelswitch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='dedup_key',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
